"""Register complete local tasks and the optional MCP transport."""

from pathlib import Path
from typing import Any


def register_task_commands(subparsers: Any) -> None:
    parser = subparsers.add_parser("task", help="Run and resume complete local plotting tasks.")
    actions = parser.add_subparsers(dest="task_action", required=True)
    capabilities = actions.add_parser("capabilities", help="Read the small task capability index, or a requested schema.")
    capabilities.add_argument("--json", action="store_true")
    capabilities.add_argument("--section", choices=("request", "response", "operations", "table_region"))
    capabilities.add_argument("--name", help="One action, response field or operation from the capability index.")
    capabilities.add_argument("--expected-contract", help="Reject schemas from a different capability fingerprint.")
    capabilities.add_argument("--full", action="store_true", help="Read all task schemas with repeated definitions factored out.")
    context = actions.add_parser("edit-context", help="Read runtime, current edit targets and selected schemas together; read-only.")
    context.add_argument("target", type=Path)
    context.add_argument("--operation", action="append", required=True, help="Advertised operation name; repeat for a batch.")
    context.add_argument("--figure", help="Registered figure identity; otherwise use the target's figure or primary figure.")
    context.add_argument("--json", action="store_true")
    region = actions.add_parser("table-region", help="Read a source-bound original cell rectangle; read-only.")
    region.add_argument("target", type=Path)
    region.add_argument("--query", type=Path, required=True)
    region.add_argument("--json", action="store_true")
    find = actions.add_parser("find", help="Find recorded creation tasks by exact original source path; read-only.")
    find.add_argument("source", type=Path)
    find.add_argument("--tasks-root", type=Path, help="Task-history directory; default is SOURCE_PARENT/.sciplot/tasks.")
    find.add_argument("--limit", type=int, default=20)
    find.add_argument("--json", action="store_true")
    start = actions.add_parser("start", help="Execute a complete structured request locally.")
    start.add_argument("--request", type=Path, required=True)
    start.add_argument("--task-dir", type=Path)
    start.add_argument("--json", action="store_true")
    start.add_argument("--full", action="store_true", help="Return the detailed task response; default is a compact receipt.")
    create = actions.add_parser("create", help="Start from original data without a request file; scientific questions remain explicit.")
    create.add_argument("source", type=Path)
    create.add_argument("--rule", dest="rule_id")
    create.add_argument("--template")
    create.add_argument("--profile", type=Path)
    create.add_argument("--out", type=Path)
    create.add_argument("--task-dir", type=Path)
    create.add_argument("--json", action="store_true")
    create.add_argument("--full", action="store_true", help="Return the detailed task response.")
    style = actions.add_parser("style", help="Preview an explicit ordinary sample color/width edit without request files.")
    style.add_argument("target", type=Path)
    samples = style.add_mutually_exclusive_group(required=True)
    samples.add_argument("--all-samples", action="store_true", help="Every exact unique ordinary sample in the selected figure.")
    samples.add_argument("--sample", action="append", help="Exact sample label; repeat to select multiple samples.")
    style.add_argument("--width", help="Native line width with unit, such as 0.7pt.")
    style.add_argument("--color", help="Native color, such as #2878B5.")
    style.add_argument("--figure", help="Registered figure identity; otherwise resolve the target's figure.")
    style.add_argument("--task-dir", type=Path)
    style.add_argument("--json", action="store_true")
    style.add_argument("--full", action="store_true", help="Return the detailed task response.")
    for name in ("inspect", "resume"):
        action = actions.add_parser(name)
        action.add_argument("target", type=Path)
        action.add_argument("--json", action="store_true")
        action.add_argument("--full", action="store_true", help="Return the detailed task response; default is a compact receipt.")
        if name == "resume":
            answer = action.add_mutually_exclusive_group(required=True)
            answer.add_argument("--response", type=Path)
            answer.add_argument("--accept-preview", action="store_true", help="Accept the reviewed preview named by --expected-operation-id.")
            answer.add_argument("--retry", action="store_true", help="Retry the existing task after resolving its reported blocker.")
            action.add_argument("--expected-operation-id", help="Required only with --accept-preview; never inferred from task history.")
    group = actions.add_parser("group", help="Run an explicit experiment list and review all native figures together.")
    group_actions = group.add_subparsers(dest="group_action", required=True)
    for name in ("capabilities", "start", "inspect", "resume"):
        action = group_actions.add_parser(name)
        action.add_argument("--json", action="store_true")
        if name == "start":
            action.add_argument("--request", type=Path, required=True)
            action.add_argument("--group-dir", type=Path, required=True)
        elif name in {"inspect", "resume"}:
            action.add_argument("target", type=Path)
            if name == "resume":
                action.add_argument("--responses", type=Path, help="JSON array of item/task-bound answers. Omit to continue pending work.")
    compare = actions.add_parser("compare", help="Compare independent native alternatives from one saved figure, then select one.")
    compare_actions = compare.add_subparsers(dest="compare_action", required=True)
    for name in ("capabilities", "start", "inspect", "resume", "select"):
        action = compare_actions.add_parser(name)
        action.add_argument("--json", action="store_true")
        if name == "start":
            action.add_argument("--request", type=Path, required=True)
            action.add_argument("--comparison-dir", type=Path, required=True)
        elif name != "capabilities":
            action.add_argument("target", type=Path)
            if name == "select":
                action.add_argument("--selection", type=Path, required=True)
    subparsers.add_parser("mcp", help="Run the optional external-AI MCP stdio server.")
