"""Declare editable fields for native Veusz axis objects."""

from sciplot_core.setting_catalog.model import COMMON_VISIBILITY, _field

AXIS_INSPECTOR_FIELDS = (
    COMMON_VISIBILITY,
    _field("axis_label", "Axis", "Label", "label", "text"),
    _field(
        "axis_min",
        "Range",
        "Minimum",
        "min",
        "number_or_auto",
        help_text='Use "Auto" for deterministic automatic range.',
    ),
    _field(
        "axis_max",
        "Range",
        "Maximum",
        "max",
        "number_or_auto",
        help_text='Use "Auto" for deterministic automatic range.',
    ),
    _field("axis_log", "Range", "Log scale", "log", "boolean", immediate=True),
    _field(
        "axis_autorange",
        "Range",
        "Auto-range padding",
        "autoRange",
        "choice",
        immediate=True,
    ),
    _field(
        "axis_reflect",
        "Placement",
        "Reflect ticks and text",
        "reflect",
        "boolean",
        immediate=True,
    ),
    _field(
        "axis_label_size",
        "Typography",
        "Label size",
        "Label/size",
        "distance",
    ),
    _field(
        "axis_label_color",
        "Typography",
        "Label color",
        "Label/color",
        "color",
    ),
    _field(
        "axis_label_bold",
        "Typography",
        "Bold label",
        "Label/bold",
        "boolean",
        immediate=True,
    ),
    _field(
        "tick_label_size",
        "Ticks",
        "Tick-label size",
        "TickLabels/size",
        "distance",
    ),
    _field(
        "tick_label_rotation",
        "Ticks",
        "Tick-label rotation",
        "TickLabels/rotate",
        "choice",
        immediate=True,
    ),
    _field(
        "tick_label_format",
        "Ticks",
        "Number format",
        "TickLabels/format",
        "text",
    ),
    _field(
        "major_tick_count",
        "Ticks",
        "Major ticks",
        "MajorTicks/number",
        "integer",
        minimum=2,
        maximum=24,
    ),
    _field(
        "major_tick_length",
        "Ticks",
        "Major tick length",
        "MajorTicks/length",
        "distance",
    ),
    _field(
        "minor_tick_count",
        "Ticks",
        "Minor ticks",
        "MinorTicks/number",
        "integer",
        minimum=0,
        maximum=100,
    ),
    _field(
        "minor_ticks_hidden",
        "Ticks",
        "Minor ticks hidden",
        "MinorTicks/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "grid_hidden",
        "Grid",
        "Major grid hidden",
        "GridLines/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "grid_color",
        "Grid",
        "Grid color",
        "GridLines/color",
        "color",
    ),
    _field(
        "grid_style",
        "Grid",
        "Grid style",
        "GridLines/style",
        "choice",
        immediate=True,
    ),
)
