"""Declare editable fields for native Veusz boxplot objects."""

from sciplot_core.setting_catalog.model import COMMON_VISIBILITY, _field

BOXPLOT_INSPECTOR_FIELDS = (
    COMMON_VISIBILITY,
    _field(
        "boxplot_values",
        "Data authority",
        "Value datasets",
        "values",
        "dataset",
        read_only=True,
    ),
    _field(
        "boxplot_width",
        "Geometry",
        "Box width",
        "fillfraction",
        "number",
        minimum=0.05,
        maximum=1.0,
        step=0.02,
    ),
    _field(
        "boxplot_outlier_marker",
        "Markers",
        "Outlier marker",
        "outliersmarker",
        "choice",
        immediate=True,
    ),
    _field(
        "boxplot_marker_size",
        "Markers",
        "Marker size",
        "markerSize",
        "distance",
    ),
    _field("boxplot_fill_color", "Fill", "Fill color", "Fill/color", "color"),
    _field(
        "boxplot_fill_transparency",
        "Fill",
        "Transparency",
        "Fill/transparency",
        "integer",
        minimum=0,
        maximum=100,
    ),
    _field(
        "boxplot_fill_hidden",
        "Fill",
        "Fill hidden",
        "Fill/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "boxplot_border_color",
        "Outline",
        "Border color",
        "Border/color",
        "color",
    ),
    _field(
        "boxplot_border_width",
        "Outline",
        "Border width",
        "Border/width",
        "distance",
    ),
    _field(
        "boxplot_border_style",
        "Outline",
        "Border style",
        "Border/style",
        "choice",
        immediate=True,
    ),
    _field(
        "boxplot_whisker_color",
        "Whiskers",
        "Whisker color",
        "Whisker/color",
        "color",
    ),
    _field(
        "boxplot_whisker_width",
        "Whiskers",
        "Whisker width",
        "Whisker/width",
        "distance",
    ),
)
