"""Declare editable fields for native Veusz key objects."""

from sciplot_core.setting_catalog.model import COMMON_VISIBILITY, _field

KEY_INSPECTOR_FIELDS = (
    COMMON_VISIBILITY,
    _field("legend_title", "Legend", "Title", "title", "text"),
    _field(
        "legend_columns",
        "Legend",
        "Columns",
        "columns",
        "integer",
        minimum=1,
        maximum=12,
    ),
    _field(
        "legend_horizontal",
        "Placement",
        "Horizontal position",
        "horzPosn",
        "choice",
        immediate=True,
    ),
    _field(
        "legend_vertical",
        "Placement",
        "Vertical position",
        "vertPosn",
        "choice",
        immediate=True,
    ),
    _field(
        "legend_manual_x",
        "Placement",
        "Manual X",
        "horzManual",
        "number",
        minimum=0.0,
        maximum=1.0,
        step=0.01,
    ),
    _field(
        "legend_manual_y",
        "Placement",
        "Manual Y",
        "vertManual",
        "number",
        minimum=0.0,
        maximum=1.0,
        step=0.01,
    ),
    _field(
        "legend_reverse",
        "Order",
        "Reverse order",
        "orderswap",
        "boolean",
        immediate=True,
    ),
    _field(
        "legend_symbol_swap",
        "Order",
        "Symbols on right",
        "symbolswap",
        "boolean",
        immediate=True,
    ),
    _field(
        "legend_text_size",
        "Typography",
        "Text size",
        "Text/size",
        "distance",
    ),
    _field(
        "legend_text_color",
        "Typography",
        "Text color",
        "Text/color",
        "color",
    ),
    _field(
        "legend_background_hidden",
        "Appearance",
        "Background hidden",
        "Background/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "legend_background_color",
        "Appearance",
        "Background color",
        "Background/color",
        "color",
    ),
    _field(
        "legend_border_hidden",
        "Appearance",
        "Border hidden",
        "Border/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "legend_border_color",
        "Appearance",
        "Border color",
        "Border/color",
        "color",
    ),
    _field(
        "legend_border_width",
        "Appearance",
        "Border width",
        "Border/width",
        "distance",
    ),
)
