"""Declare editable fields for native Veusz label objects."""

from sciplot_core.setting_catalog.model import COMMON_VISIBILITY, _field

LABEL_INSPECTOR_FIELDS = (
    COMMON_VISIBILITY,
    _field("annotation_text", "Annotation", "Text", "label", "text"),
    _field(
        "annotation_x",
        "Position",
        "X position",
        "xPos",
        "scalar_list",
        minimum=-10.0,
        maximum=10.0,
    ),
    _field(
        "annotation_y",
        "Position",
        "Y position",
        "yPos",
        "scalar_list",
        minimum=-10.0,
        maximum=10.0,
    ),
    _field(
        "annotation_coordinate_mode",
        "Position",
        "Coordinate mode",
        "positioning",
        "choice",
        immediate=True,
    ),
    _field(
        "annotation_align_horizontal",
        "Position",
        "Horizontal alignment",
        "alignHorz",
        "choice",
        immediate=True,
    ),
    _field(
        "annotation_align_vertical",
        "Position",
        "Vertical alignment",
        "alignVert",
        "choice",
        immediate=True,
    ),
    _field(
        "annotation_angle",
        "Position",
        "Rotation",
        "angle",
        "number",
        minimum=-360.0,
        maximum=360.0,
        step=5.0,
    ),
    _field(
        "annotation_text_size",
        "Typography",
        "Text size",
        "Text/size",
        "distance",
    ),
    _field(
        "annotation_text_color",
        "Typography",
        "Text color",
        "Text/color",
        "color",
    ),
    _field(
        "annotation_bold",
        "Typography",
        "Bold",
        "Text/bold",
        "boolean",
        immediate=True,
    ),
    _field(
        "annotation_italic",
        "Typography",
        "Italic",
        "Text/italic",
        "boolean",
        immediate=True,
    ),
)
