"""Declare editable fields for native Veusz xy objects."""

from sciplot_core.setting_catalog.model import COMMON_VISIBILITY, _field

XY_INSPECTOR_FIELDS = (
    COMMON_VISIBILITY,
    _field("series_name", "Series", "Legend name", "key", "text"),
    _field(
        "series_x_data",
        "Data authority",
        "X data",
        "xData",
        "dataset",
        read_only=True,
    ),
    _field(
        "series_y_data",
        "Data authority",
        "Y data",
        "yData",
        "dataset",
        read_only=True,
    ),
    _field(
        "series_marker",
        "Markers",
        "Marker",
        "marker",
        "choice",
        immediate=True,
    ),
    _field(
        "series_marker_size",
        "Markers",
        "Marker size",
        "markerSize",
        "distance",
    ),
    _field("series_color", "Markers", "Master color", "color", "color"),
    _field(
        "series_line_hidden",
        "Line",
        "Line hidden",
        "PlotLine/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "series_line_color",
        "Line",
        "Line color",
        "PlotLine/color",
        "color",
    ),
    _field(
        "series_line_width",
        "Line",
        "Line width",
        "PlotLine/width",
        "distance",
    ),
    _field(
        "series_line_style",
        "Line",
        "Line style",
        "PlotLine/style",
        "choice",
        immediate=True,
    ),
    _field(
        "series_interpolation",
        "Line",
        "Interpolation",
        "PlotLine/interpType",
        "choice",
        immediate=True,
    ),
    _field(
        "series_fill_hidden",
        "Marker fill",
        "Fill hidden",
        "MarkerFill/hide",
        "boolean",
        immediate=True,
    ),
    _field(
        "series_fill_color",
        "Marker fill",
        "Fill color",
        "MarkerFill/color",
        "color",
    ),
    _field(
        "series_fill_transparency",
        "Marker fill",
        "Transparency",
        "MarkerFill/transparency",
        "integer",
        minimum=0,
        maximum=100,
    ),
    _field(
        "series_error_style",
        "Errors",
        "Error style",
        "errorStyle",
        "choice",
        immediate=True,
    ),
)
