from __future__ import annotations

from pathlib import Path
from typing import Any


def artifact_manifest_payload(*, output_dir: str | Path, artifacts: list[dict[str, Any]]) -> dict[str, Any]:
    root = Path(output_dir)
    return {
        "artifact_kind": "manifest",
        "output_dir": str(root),
        "artifacts": artifacts,
        "count": len(artifacts),
        "help": "Manifest-backed artifact set generated by SciPlot export target runtime helpers.",
    }


__all__ = ["artifact_manifest_payload"]
