from __future__ import annotations

GENERIC_TEMPLATE_PARSE_STRATEGY = "structured:curve_metrics_columns"
AUTO_FILTER_KEEP_COUNT = 5
AUTO_FILTER_METRIC_TRIAD = ("Strength", "Modulus", "Elongation")
FILTERED_WORKBOOK_DECIMAL_PLACES = 2
FILTERED_WORKBOOK_CURVE_DECIMAL_PLACES = 4

__all__ = [
    "AUTO_FILTER_KEEP_COUNT",
    "AUTO_FILTER_METRIC_TRIAD",
    "FILTERED_WORKBOOK_CURVE_DECIMAL_PLACES",
    "FILTERED_WORKBOOK_DECIMAL_PLACES",
    "GENERIC_TEMPLATE_PARSE_STRATEGY",
]
