"""Declare rheology rules."""

from __future__ import annotations

from sciplot_core.policy import (
    CURVE_RENDER_OPTIONS,
    DEFAULT_LOG_TICK_FORMAT,
    RHEOLOGY_FREQUENCY_RENDER_OPTIONS,
    RHEOLOGY_TEMPERATURE_RENDER_OPTIONS,
)
from sciplot_core.materials_rules.models import (
    AxisSpec,
    AnalysisSpec,
    SemanticRule,
    _rule,
)
from sciplot_core.materials_rules.unit_data import (
    NORMALIZED_STRESS_RATIO_DISPLAY_LABEL,
)

from sciplot_core.materials_rules.catalog_axes import (
    RHEOLOGY_X_FREQUENCY,
    RHEOLOGY_X_TEMPERATURE,
    TIME_AXIS,
)

RHEOLOGY_RULES: tuple[SemanticRule, ...] = (
    _rule(
        "rheology_frequency_sweep",
        "rheology_frequency",
        "rheology_dma",
        "point_line",
        RHEOLOGY_X_FREQUENCY,
        AxisSpec(
            "Storage modulus",
            "Pa",
            "Storage modulus, G′ (Pa)",
            aliases=("storage modulus", "G'", "G′"),
            priority_labels=("G'", "Storage Modulus", "G′", 'G"', "tanδ"),
            scale="log",
        ),
        keywords=("frequencysweep", "angularfrequency", "pinlv"),
        path_keywords=("/freq/", "pinlv"),
        column_aliases=(
            "angular frequency",
            "storage modulus",
            "loss modulus",
            "loss factor",
            "complex modulus",
        ),
        vendor_models=("frequency_metric_sheet",),
        experiment_families=("rheology",),
        render_options=RHEOLOGY_FREQUENCY_RENDER_OPTIONS,
        analysis=(
            AnalysisSpec(
                "terminal_modulus",
                "storage modulus G′ at the lowest finite angular frequency",
                ("angular frequency", "storage modulus"),
                "Pa",
            ),
        ),
        fixture_path="tests/fixtures/real_world/rheology_frequency_sweep",
        fixture_status="ready",
        priority=20,
        reason="Rheology frequency sweep with modulus/viscosity metrics.",
        render_adapter="rheology",
        scientific_source_adapter="rheology_frequency",
        figure_plan_adapter="rheology_frequency",
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_temperature_sweep",
        "rheology_temperature_sweep",
        "rheology_dma",
        "point_line",
        RHEOLOGY_X_TEMPERATURE,
        AxisSpec(
            "Storage modulus",
            "Pa",
            "G′ (Pa)",
            aliases=("storage modulus", "G'", "G′", "complex modulus", "|G*|"),
            priority_labels=("G'", "Storage Modulus", "|G*|", "Complex Modulus", 'G"'),
            scale="log",
        ),
        keywords=("rheologytemperaturesweep", "temperaturesweep", "温度扫描"),
        path_keywords=("/temp/", "rheology_temperature"),
        column_aliases=("temperature", "storage modulus", "complex modulus"),
        render_options=RHEOLOGY_TEMPERATURE_RENDER_OPTIONS,
        analysis=(
            AnalysisSpec(
                "maximum_tan_delta",
                "maximum finite loss factor per sample; not interpreted as Tg",
                ("temperature", "tan delta"),
                "1",
            ),
            AnalysisSpec(
                "temperature_at_maximum_tan_delta_C",
                "temperature at the maximum finite loss factor; endpoint maxima are retained and not interpreted as Tg",
                ("temperature", "tan delta"),
                "C",
            ),
            AnalysisSpec(
                "softening_temperature_candidate",
                "temperature at the most negative discrete storage-modulus gradient",
                ("temperature", "storage modulus"),
                "C",
            ),
        ),
        available_metrics=(
            "maximum_tan_delta",
            "temperature_at_maximum_tan_delta_C",
            "softening_temperature_candidate",
        ),
        fixture_path="tests/fixtures/real_world/rheology_temperature_sweep",
        fixture_status="ready",
        priority=10,
        reason="Rheology/DMA temperature sweep with modulus priority G′, |G*|, then G″.",
        render_adapter="rheology",
        scientific_source_adapter="rheology_temperature",
        figure_plan_adapter="rheology_temperature",
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_time_sweep",
        "rheology_time_sweep",
        "rheology_dma",
        "point_line",
        TIME_AXIS,
        AxisSpec(
            "Complex modulus",
            "Pa",
            "Complex modulus, |G*| (Pa)",
            aliases=("complex modulus", "complex shear modulus", "|G*|"),
        ),
        keywords=("timesweep", "time sweep"),
        path_keywords=("rheology_time_sweep", "time_sweep"),
        analysis=(
            AnalysisSpec(
                "peak_modulus_time_s",
                "time at maximum complex modulus |G*|",
                ("time", "complex modulus"),
                "s",
            ),
        ),
        fixture_path="tests/fixtures/real_world/rheology_time_sweep",
        fixture_status="ready",
        priority=28,
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_strain_sweep",
        "rheology_strain_sweep",
        "rheology_dma",
        "point_line",
        AxisSpec(
            "Strain",
            "%",
            "Strain (%)",
            aliases=("strain", "shear strain", "γ"),
            scale="log",
        ),
        AxisSpec(
            "Storage modulus",
            "Pa",
            "Storage modulus, G′ (Pa)",
            aliases=("storage modulus", "G'", "G′"),
            priority_labels=("G'", "Storage Modulus", "G′", 'G"', "tanδ"),
            scale="log",
        ),
        keywords=("strainsweep", "amplitude sweep"),
        path_keywords=("rheology_strain_sweep", "strain_sweep"),
        analysis=(
            AnalysisSpec(
                "peak_modulus_strain_percent",
                "strain at maximum storage modulus G′",
                ("strain", "storage modulus"),
                "%",
            ),
        ),
        fixture_path="tests/fixtures/real_world/rheology_strain_sweep",
        fixture_status="ready",
        priority=28,
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_stress_sweep",
        "rheology_stress_sweep",
        "rheology_dma",
        "point_line",
        AxisSpec(
            "Stress",
            "Pa",
            "Stress (Pa)",
            aliases=("stress", "shear stress"),
            scale="log",
        ),
        AxisSpec(
            "Storage modulus",
            "Pa",
            "Storage modulus, G′ (Pa)",
            aliases=("storage modulus", "G'", "G′"),
            priority_labels=("G'", "Storage Modulus", "G′", 'G"', "tanδ"),
            scale="log",
        ),
        keywords=("stresssweep", "stress sweep"),
        path_keywords=("rheology_stress_sweep", "stress_sweep"),
        analysis=(
            AnalysisSpec(
                "peak_modulus_stress_Pa",
                "stress at maximum storage modulus G′",
                ("stress", "storage modulus"),
                "Pa",
            ),
        ),
        fixture_path="tests/fixtures/real_world/rheology_stress_sweep",
        fixture_status="ready",
        priority=28,
        reason=(
            "Shared amplitude-sweep parser using the instrument-reported measured shear-stress axis; the evidence record does not claim a stress-controlled protocol."
        ),
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_creep",
        "rheology_creep",
        "rheology_dma",
        "curve",
        TIME_AXIS,
        AxisSpec(
            "Creep compliance",
            "1/Pa",
            "Creep compliance, J(t) (Pa⁻¹)",
            aliases=("creep compliance",),
        ),
        keywords=("creep", "creeptest", "creepcompliance"),
        path_keywords=("creep",),
        analysis=(
            AnalysisSpec(
                "final_compliance", "last finite J(t)", ("Creep compliance",), "1/Pa"
            ),
            AnalysisSpec(
                "recovery_ratio",
                "recovery segment if available",
                ("Creep compliance",),
                "fraction",
            ),
        ),
        fixture_path="tests/fixtures/real_world/rheology_creep",
        fixture_status="ready",
        priority=30,
        preparation_adapter="rheology",
    ),
    _rule(
        "rheology_stress_relaxation",
        "rheology_stress_relaxation",
        "stress_relaxation",
        "curve",
        AxisSpec("Time", "s", "Time (s)", aliases=("time", "时间"), scale="log"),
        AxisSpec(
            "Normalized stress",
            "sigma/sigma0",
            NORMALIZED_STRESS_RATIO_DISPLAY_LABEL,
            aliases=("shear stress", "relaxation modulus", "stress"),
        ),
        keywords=(
            "stressrelaxation",
            "stresssrelaxation",
            "relaxationtest",
            "relaxationmodulus",
            "stepstrain",
        ),
        path_keywords=("relax", "stresss relaxation"),
        analysis=(
            AnalysisSpec(
                "final_normalized_value",
                "last finite value from every canonical paired normalized trace",
                ("stress",),
                "sigma/sigma0",
            ),
            AnalysisSpec(
                "t50_s",
                "post-maximum interpolated time to normalized value <= 0.5 for every canonical paired trace",
                ("stress", "time"),
                "s",
            ),
        ),
        render_options={
            **CURVE_RENDER_OPTIONS,
            "xscale": "log",
            "x_tick_format": DEFAULT_LOG_TICK_FORMAT,
            "minor_tick_count": 10,
            "y_min": -0.05,
            "y_max": 1.05,
            "y_ticks": [0.0, 0.25, 0.5, 0.75, 1.0],
        },
        fixture_path="tests/fixtures/real_world/rheology_stress_relaxation",
        fixture_status="ready",
        priority=25,
        scientific_source_adapter="stress_relaxation",
        figure_plan_adapter="registered_single_curve",
        preparation_adapter="rheology",
    ),
)
