"""Declare canonical display aliases used while interpreting source tables."""

from __future__ import annotations


LABEL_ALIASES_SOURCE = {
    "ω": "ω",
    "Ω": "ω",
    "σ": "σ",
    "γ": "γ",
    "angular frequency": "ω",
    "frequency": "ω",
    "storage modulus": "G'",
    "g'": "G'",
    "loss modulus": 'G"',
    'g"': 'G"',
    "loss factor": "tanδ",
    "tan delta": "tanδ",
    "tandelta": "tanδ",
    "complex viscosity": "|η*|",
    "complex viscocity": "|η*|",
    "time": "Time",
    "temperature": "Temperature",
    "shear stress": "σ",
    "stress": "σ",
    "shear strain": "γ",
    "strain": "Strain",
    "wavenumber": "Wavenumber",
    "wavenumbers": "Wavenumber",
    "chemical shift": "Chemical shift",
    "intensity": "Intensity",
    "transmittance": "Transmittance",
    "absorbance": "Absorbance",
    "heat flow": "Heat flow",
    "weight": "Weight",
    "mass": "Mass",
    "weight loss": "Weight loss",
    "mass loss": "Mass loss",
    "count": "Counts",
    "counts": "Counts",
    "2theta": "2θ",
    "2 theta": "2θ",
    "2θ": "2θ",
    "σ/σ0": r"$\sigma/\sigma_0$",
    "σ/σo": r"$\sigma/\sigma_0$",
    "sigma/sigma0": r"$\sigma/\sigma_0$",
    "sigma/sigmao": r"$\sigma/\sigma_0$",
    "tensile modulus": "Tensile modulus",
    "tensile strength": "Tensile strength",
}


UNIT_ALIASES_SOURCE = {
    "mpa": "MPa",
    "pa": "Pa",
    "kpa": "kPa",
    "gpa": "GPa",
    "ppm": "ppm",
    "[ppm]": "ppm",
    "a.u.": "a.u.",
    "a.u": "a.u.",
    "au": "a.u.",
    "arb. units": "a.u.",
    "arbitrary units": "a.u.",
    "count": "counts",
    "counts": "counts",
    "[count]": "counts",
    "[counts]": "counts",
    "rad/s": r"rad$\cdot$s$^{-1}$",
    "rad.s-1": r"rad$\cdot$s$^{-1}$",
    "rad.s^-1": r"rad$\cdot$s$^{-1}$",
    "rad s-1": r"rad$\cdot$s$^{-1}$",
    "rad s^-1": r"rad$\cdot$s$^{-1}$",
    "rad.s−1": r"rad$\cdot$s$^{-1}$",
    "rad s−1": r"rad$\cdot$s$^{-1}$",
    "mpa.s": r"mPa$\cdot$s",
    "mpa s": r"mPa$\cdot$s",
    "mpa/s": r"MPa$\cdot$s$^{-1}$",
    "N m": "N·m",
    "N.m": "N·m",
    "N·m": "N·m",
    "newton meter": "N·m",
    "newton metre": "N·m",
    "pa.s": r"Pa$\cdot$s",
    "pa s": r"Pa$\cdot$s",
    "cm-1": r"cm$^{-1}$",
    "cm^-1": r"cm$^{-1}$",
    "cm−1": r"cm$^{-1}$",
    "1/cm": r"cm$^{-1}$",
    "[cm-1]": r"cm$^{-1}$",
    "[cm^-1]": r"cm$^{-1}$",
    "degc": "°C",
    "°c": "°C",
    "celsius": "°C",
    "degree": "°",
    "degrees": "°",
    "[s]": "s",
    "s": "s",
    "[%]": "%",
    "%": "%",
    "wt%": "%",
    "mass %": "%",
    "weight %": "%",
    "σ/σ0": r"$\sigma/\sigma_0$",
    "σ/σo": r"$\sigma/\sigma_0$",
    "sigma/sigma0": r"$\sigma/\sigma_0$",
    "sigma/sigmao": r"$\sigma/\sigma_0$",
    r"$\sigma/\sigma_0$": r"$\sigma/\sigma_0$",
    "G/G0": r"$G/G_0$",
    "G/Go": r"$G/G_0$",
    r"$G/G_0$": r"$G/G_0$",
    "[pa]": "Pa",
    "[mpa]": "MPa",
    "[kpa]": "kPa",
    "[gpa]": "GPa",
}


__all__ = ["LABEL_ALIASES_SOURCE", "UNIT_ALIASES_SOURCE"]
