"""The minimal backend contract; no protocol or persistence dependencies."""

from pathlib import Path
from typing import Any, Protocol


class PlotOpener(Protocol):
    def open(self, target: Path, figure_id: str | None = None) -> dict[str, Any]: ...


class PlotCreator(PlotOpener, Protocol):
    def open_created(self, target: Path, *, series_ids: dict[str, str], recipe: dict[str, Any],
                     figure_id: str | None = None) -> dict[str, Any]: ...

    def patch(self, plot: Path, request: dict[str, Any]) -> dict[str, Any]: ...

    def describe(self, plot: Path) -> dict[str, Any]: ...

    def export(self, plot: Path) -> dict[str, Any]: ...


class PlotBackend(Protocol):
    def import_project(self, project: Path, figure_id: str | None = None,
                       plot_id: str | None = None) -> tuple[dict[str, Any], dict[str, Any]]: ...

    def fingerprint(self, binding: dict[str, Any]) -> dict[str, Any]: ...

    def preview(self, document: dict[str, Any], binding: dict[str, Any],
                new_document: dict[str, Any], diff: list[dict[str, Any]],
                output: Path) -> dict[str, Any]: ...

    def apply(self, binding: dict[str, Any], review: dict[str, Any]) -> dict[str, Any]: ...

    def refresh_binding(self, binding: dict[str, Any], apply_result: dict[str, Any]) -> dict[str, Any]: ...

    def export(self, binding: dict[str, Any]) -> dict[str, Any]: ...

    def render(self, binding: dict[str, Any], output: Path) -> dict[str, Any]: ...
