"""Focused evidence for external project control and first-run plan binding."""

from sciplot_core.verification.owner_model import ChangedOwner
from sciplot_core.verification.type_gate_owners import ARCHITECTURE_CORE_TARGETS


EXTERNAL_AI_OWNERS = (
    ChangedOwner(
        owner_id="automation_baseline_evidence",
        exact_paths=frozenset(
            {
                "src/sciplot_core/automation_baseline.py",
                "src/sciplot_core/automation_baseline_identity_validation.py",
                "src/sciplot_core/automation_baseline_probe.py",
                "src/sciplot_core/automation_baseline_schema.py",
                "src/sciplot_core/automation_baseline_validation.py",
                "src/sciplot_core/automation_baseline_validation_utils.py",
            }
        ),
        owned_test_paths=frozenset({"tests/test_automation_baseline.py"}),
        pytest_targets=(
            "tests/test_automation_baseline.py",
            "tests/test_automation_states.py",
            "tests/test_rule_invocation_contract.py::test_rules_plan_and_autoplot_share_one_stale_rule_decision",
            "tests/test_plan_preview.py::test_plan_preview_blocks_uncertified_rule_before_source_inspection",
            "tests/test_autoplot_run.py::test_run_autoplot_returns_v2_rule_repair_without_project_or_write",
            "tests/test_publish_state.py::test_publish_state_preserves_a_scientific_confirmation_blocker",
            "tests/test_frontend_topology.py::test_package_has_one_cli_and_no_standalone_frontend_entrypoint",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="expected_plan_execution",
        exact_paths=frozenset(
            {
                "src/sciplot_core/plan_identity.py",
                "src/sciplot_core/plan_preview.py",
                "src/sciplot_core/autoplot/run.py",
                "src/sciplot_core/cli/parsers/rendering.py",
                "src/sciplot_core/cli/dispatch/rendering.py",
            }
        ),
        owned_test_paths=frozenset({"tests/test_plan_identity.py"}),
        pytest_targets=(
            "tests/test_plan_identity.py",
            "tests/test_plan_preview.py",
            "tests/test_rule_invocation_contract.py",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="saved_project_query",
        exact_paths=frozenset(
            {
                "src/sciplot_core/studio_core/project_query.py",
                "src/sciplot_core/studio_core/project_query_evidence.py",
                "src/sciplot_core/studio_core/project_query_paths.py",
            }
        ),
        owned_test_paths=frozenset(
            {"tests/test_project_query.py", "tests/test_project_query_native.py"}
        ),
        pytest_targets=(
            "tests/test_project_query.py",
            "tests/test_project_query_native.py",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="native_document_edit",
        exact_paths=frozenset(
            {
                "src/sciplot_core/native_settings.py",
                "src/sciplot_core/studio_core/document_edit.py",
                "src/sciplot_core/studio_core/document_edit_commit.py",
                "src/sciplot_core/studio_core/document_edit_policy.py",
                "src/sciplot_core/studio_core/document_edit_state.py",
                "src/sciplot_core/veusz_worker/document_edit.py",
                "src/sciplot_core/veusz_worker/cli.py",
                "src/sciplot_core/veusz_worker/operations.py",
                "src/sciplot_gui/studio_assistant/proposal_application.py",
                "src/sciplot_gui/studio_assistant/selection.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_document_edit.py",
                "tests/test_document_edit_native.py",
                "tests/test_document_edit_policy.py",
                "tests/test_native_document_edit.py",
            }
        ),
        pytest_targets=(
            "tests/test_document_edit.py",
            "tests/test_document_edit_native.py",
            "tests/test_document_edit_policy.py",
            "tests/test_native_document_edit.py",
            "tests/test_project_query.py",
            "tests/test_assistant_contract.py",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="native_project_session",
        exact_paths=frozenset(
            {
                "src/sciplot_core/studio_core/project_session.py",
                "src/sciplot_core/studio.py",
            }
        ),
        owned_test_paths=frozenset({"tests/test_project_session.py"}),
        pytest_targets=(
            "tests/test_project_session.py",
            "tests/test_document_edit.py",
            "tests/test_document_edit_native.py",
            "tests/test_project_source_update_transaction.py",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="external_project_control_cli",
        exact_paths=frozenset(
            {
                "src/sciplot_core/cli/dispatch/project.py",
                "src/sciplot_core/cli/dispatch/project_create.py",
                "src/sciplot_core/cli/parsers/project.py",
                "src/sciplot_core/cli/parsers/builder.py",
                "src/sciplot_core/cli/parsers/interfaces.py",
                "src/sciplot_core/cli/dispatch/interfaces.py",
            }
        ),
        owned_test_paths=frozenset(
            {"tests/test_project_control_cli.py", "tests/test_project_create_cli.py"}
        ),
        pytest_targets=(
            "tests/test_project_control_cli.py",
            "tests/test_project_create_cli.py",
            "tests/test_project_query.py",
            "tests/test_document_edit.py",
            "tests/test_project_session.py",
            "tests/test_cli_surface.py",
            *ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        release_gates=("full_pytest",),
    ),
)
