"""Source-controlled changed-owner to focused-evidence mapping."""

from __future__ import annotations

from sciplot_core.verification.axis_owners import GENERIC_AXIS_OWNERS
from sciplot_core.verification.owner_model import ChangedOwner
_ARCHITECTURE_CORE_TARGETS = (
    "tests/test_architecture_boundaries.py::test_ordinary_source_files_stay_within_the_size_boundary",
    "tests/test_architecture_boundaries.py::test_first_party_import_graph_is_acyclic",
)

CHANGED_OWNERS = (
    ChangedOwner(
        owner_id="documentation_contract",
        path_prefixes=("docs/",),
        exact_paths=frozenset(
            {
                "AGENTS.md",
                "DEVELOPMENT_LOG.md",
                "DEVELOPMENT_ROADMAP.md",
                "README.md",
            }
        ),
        owned_test_paths=frozenset({"tests/test_documentation_contract.py"}),
        pytest_targets=("tests/test_documentation_contract.py",),
    ),
    ChangedOwner(
        owner_id="validated_readiness_registry",
        path_prefixes=("src/sciplot_core/readiness/",),
        exact_paths=frozenset({"src/sciplot_core/validated_envelopes.json"}),
        owned_test_paths=frozenset({"tests/test_readiness_registry_merge.py"}),
        pytest_targets=(
            "tests/test_readiness_registry_merge.py",
            "tests/test_rule_certification.py",
            "tests/test_cli_surface.py::test_readiness_merge_parser_accepts_base_summary_and_output",
            "tests/test_cli_surface.py::test_readiness_merge_cli_writes_the_same_registry_and_reports_selection",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="changed_verification",
        path_prefixes=("src/sciplot_core/verification/",),
        exact_paths=frozenset(
            {
                "src/sciplot_core/cli/parsers/diagnostics.py",
                "src/sciplot_core/cli/dispatch/diagnostics.py",
                "src/sciplot_core/doctor/payload.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_changed_verification.py",
                "tests/test_cli_surface.py",
                "tests/test_doctor_contract_topology.py",
            }
        ),
        pytest_targets=(
            "tests/test_changed_verification.py",
            "tests/test_cli_surface.py",
            "tests/test_doctor_contract_topology.py",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        handoff_gates=("doctor",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="verification_policy",
        exact_paths=frozenset(
            {
                "pyproject.toml",
                "skill/SKILL.md",
                "tests/conftest.py",
            }
        ),
        pytest_targets=(
            "tests/test_documentation_contract.py",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        handoff_gates=("doctor",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="skill_wrapper",
        exact_paths=frozenset(
            {"skill/scripts/sciplot", "tests/test_skill_wrapper_cwd.py"}
        ),
        owned_test_paths=frozenset({"tests/test_skill_wrapper_contract.py"}),
        pytest_targets=("tests/test_skill_wrapper_contract.py",),
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="ai_autoplot_invocation",
        exact_paths=frozenset(
            {
                "src/sciplot_core/autoplot/run.py",
                "src/sciplot_core/cli/dispatch/rendering.py",
                "src/sciplot_core/cli/parsers/rendering.py",
                "src/sciplot_core/materials_rules/catalog.py",
                "src/sciplot_core/materials_rules/comparison_rules.py",
                "src/sciplot_core/materials_rules/dma_temperature_rules.py",
                "src/sciplot_core/materials_rules/mechanical_rules.py",
                "src/sciplot_core/materials_rules/models.py",
                "src/sciplot_core/materials_rules/rheology_rules.py",
                "src/sciplot_core/materials_rules/spectroscopy_rules.py",
                "src/sciplot_core/materials_rules/swelling_rules.py",
                "src/sciplot_core/materials_rules/thermal_rules.py",
                "src/sciplot_core/workflow/__init__.py",
                "src/sciplot_core/workflow/one_step_entry.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_autoplot_run.py",
                "tests/test_rule_invocation_contract.py",
                "tests/test_semantic_preparation_dispatch.py",
                "tests/test_style_template_contract.py",
                "tests/test_workflow_bundle_dispatch.py",
            }
        ),
        pytest_targets=(
            "tests/test_cli_surface.py::test_autoplot_cli_forwards_explicit_rule_and_presentation_template",
            "tests/test_autoplot_run.py",
            "tests/test_rule_invocation_contract.py",
            "tests/test_semantic_preparation_dispatch.py",
            "tests/test_workflow_bundle_dispatch.py",
            "tests/test_style_template_contract.py::test_autoplot_preserves_an_explicit_rule_and_supported_presentation_template",
            "tests/test_style_template_contract.py::test_autoplot_rejects_an_empty_explicit_rule_before_project_creation",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="materials_analysis",
        exact_paths=frozenset(
            {
                "src/sciplot_core/analysis_contract_probe.py",
                "src/sciplot_core/materials_rules/analysis.py", "src/sciplot_core/materials_rules/impact_metrics.py",
            }
        ),
        owned_test_paths=frozenset({"tests/test_dtg_analysis.py", "tests/test_impact_unit_evidence.py"}),
        pytest_targets=("tests/test_dtg_analysis.py", "tests/test_impact_unit_evidence.py"),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="typed_core_contracts",
        path_prefixes=(
            "src/sciplot_core/figure_plan/",
            "src/sciplot_core/foundation/",
        ),
        exact_paths=frozenset(
            {
                "src/sciplot_core/autoplot/evidence.py",
                "src/sciplot_core/autoplot/publish_integrity.py",
                "src/sciplot_core/autoplot/summary.py",
                "src/sciplot_core/delivery/package_builder.py",
                "src/sciplot_core/delivery/package_validation.py",
                "src/sciplot_core/delivery/plan_binding.py",
                "src/sciplot_core/json_contract.py",
                "src/sciplot_core/publish_state.py",
                "src/sciplot_core/study_model/experiment_plans.py",
                "src/sciplot_core/study_model/package_contract.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_autoplot_evidence.py",
                "tests/test_foundation_text_values.py",
                "tests/test_output_package_contract.py",
                "tests/test_publish_state.py",
                "tests/test_dsc_adapter_dispatch.py",
                "tests/test_resolved_figure_plan.py",
                "tests/test_resolved_mechanical_figure_plan.py",
                "tests/test_resolved_performance_figure_plan.py",
                "tests/test_resolved_temperature_figure_plan.py",
                "tests/test_study_model_artifact_binding.py",
            }
        ),
        pytest_targets=(
            "tests/test_autoplot_evidence.py",
            "tests/test_foundation_text_values.py",
            "tests/test_output_package_contract.py",
            "tests/test_publish_state.py",
            "tests/test_dsc_adapter_dispatch.py",
            "tests/test_resolved_figure_plan.py",
            "tests/test_resolved_mechanical_figure_plan.py",
            "tests/test_resolved_performance_figure_plan.py",
            "tests/test_resolved_temperature_figure_plan.py",
            "tests/test_study_model_artifact_binding.py",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        mypy_required=True,
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="scientific_transform",
        path_prefixes=("src/sciplot_core/semantic_sources/ftir_", "src/sciplot_core/semantic_sources/gpc_", "src/sciplot_core/semantic_sources/panalytical_", "src/sciplot_core/semantic_sources/scientific_source"),
        exact_paths=frozenset(
            {
                "src/sciplot_core/plan_preview.py",
                "src/sciplot_core/scientific_review.py",
                "src/sciplot_core/scientific_review_ledger.py",
                "src/sciplot_core/semantic.py",
                "src/sciplot_core/semantic_sources/classification.py",
                "src/sciplot_core/figure_plan/dma_temperature_resolution.py",
                "src/sciplot_core/figure_plan/frequency_resolution.py",
                "src/sciplot_core/figure_plan/single_curve_resolution.py",
                "src/sciplot_core/figure_plan/temperature_resolution.py",
                "src/sciplot_core/figure_plan/resolution.py",
                "src/sciplot_core/semantic_sources/dma_sources.py",
                "src/sciplot_core/semantic_sources/dma_temperature_transform.py",
                "src/sciplot_core/semantic_sources/models.py", "src/sciplot_core/semantic_sources/numeric_separators.py",
                "src/sciplot_core/semantic_sources/impact_sources.py", "src/sciplot_core/semantic_sources/prepare_curve_families.py", "src/sciplot_core/semantic_sources/prepare_mechanical.py", "src/sciplot_core/semantic_sources/swelling_sources.py", "src/sciplot_core/semantic_sources/torque_event_selection.py", "src/sciplot_core/semantic_sources/torque_sources.py",
                "src/sciplot_core/semantic_sources/prepare_rheology.py",
                "src/sciplot_core/semantic_sources/preparation_context.py",
                "src/sciplot_core/request_contract.py",
                "src/sciplot_core/semantic_sources/paired_curve_table_metadata.py",
                "src/sciplot_core/semantic_sources/registered_paired_curve_contract.py",
                "src/sciplot_core/semantic_sources/rheology_interval.py",
                "src/sciplot_core/semantic_sources/rheology_sweep_domain.py",
                "src/sciplot_core/semantic_sources/rheology_sweep_sources.py",
                "src/sciplot_core/semantic_sources/rheology_temperature_domain.py",
                "src/sciplot_core/semantic_sources/registered_paired_curve_transform.py",
                "src/sciplot_core/semantic_sources/scientific_transform.py",
                "src/sciplot_core/semantic_sources/stress_relaxation_contract.py",
                "src/sciplot_core/semantic_sources/stress_relaxation_evidence.py",
                "src/sciplot_core/semantic_sources/stress_relaxation_hold.py",
                "src/sciplot_core/semantic_sources/stress_relaxation_sources.py",
                "src/sciplot_core/semantic_sources/stress_relaxation_transform.py",
                "src/sciplot_core/semantic_sources/table_scanning.py",
                "src/sciplot_core/semantic_sources/table_source_files.py",
                "src/sciplot_core/semantic_sources/tga_transform.py",
                "src/sciplot_core/semantic_sources/tensile_export_identity.py",
                "src/sciplot_core/source_tables/raw_readers.py",
                "src/sciplot_core/studio_core/semantic_source.py",
                "src/sciplot_core/studio_core/source_bound_prepare.py",
                "src/sciplot_core/workflow/auto_split.py",
                "src/sciplot_core/workflow/dma_named_recipe.py",
                "src/sciplot_core/workflow/dma_temperature_bundle.py",
                "src/sciplot_core/workflow/dma_temperature_plan.py",
                "src/sciplot_core/workflow/legacy_route_rendering.py",
                "src/sciplot_core/workflow/request_publish.py",
                "src/sciplot_core/workflow/request_rendering.py",
                "src/sciplot_core/workflow/request_run.py",
                "src/sciplot_core/workflow/scientific_source_resolution.py",
                "src/sciplot_core/workflow/source_binding.py",
                "src/sciplot_gui/studio_project_status/builder.py",
                "src/sciplot_gui/studio_project_status/messages.py",
                "src/sciplot_gui/studio_project/context.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_plan_preview.py",
                "tests/test_dma_temperature_scientific_transform.py",
                "tests/test_ftir_scientific_transform.py",
                "tests/test_resolved_dma_temperature_plan.py",
                "tests/test_resolved_frequency_figure_plan.py",
                "tests/test_resolved_temperature_figure_plan.py",
                "tests/test_rheology_sweep_domain.py",
                "tests/test_registered_single_curve_figure_plan.py",
                "tests/test_saxs_source_contract.py",
                "tests/test_scientific_review.py",
                "tests/test_scientific_source_pipeline.py",
                "tests/test_scientific_transform_contract.py",
                "tests/test_semantic_multitest_contract.py",
                "tests/test_semantic_preparation_dispatch.py",
                "tests/test_studio_project_context.py",
                "tests/test_impact_unit_evidence.py", "tests/test_swelling_source_contract.py", "tests/test_tga_scientific_transform.py", "tests/test_torque_source_contract.py",
            }
        ),
        pytest_targets=(
            "tests/test_plan_preview.py",
            "tests/test_dma_temperature_scientific_transform.py",
            "tests/test_ftir_scientific_transform.py",
            "tests/test_resolved_dma_temperature_plan.py",
            "tests/test_resolved_frequency_figure_plan.py::test_frequency_directory_plan_uses_parser_selected_text_sources",
            "tests/test_resolved_temperature_figure_plan.py",
            "tests/test_rheology_sweep_domain.py",
            "tests/test_registered_single_curve_figure_plan.py",
            "tests/test_saxs_source_contract.py",
            "tests/test_scientific_review.py",
            "tests/test_scientific_source_pipeline.py",
            "tests/test_dma_named_recipe_plan_binding.py::test_dma_named_recipe_preflight_binds_the_exact_plan",
            "tests/test_scientific_transform_contract.py",
            "tests/test_semantic_multitest_contract.py",
            "tests/test_semantic_preparation_dispatch.py",
            "tests/test_studio_project_context.py",
            "tests/test_impact_unit_evidence.py", "tests/test_swelling_source_contract.py", "tests/test_tga_scientific_transform.py", "tests/test_torque_source_contract.py",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        final_milestone_gates=("smoke",),
        release_gates=("acceptance_rules", "full_pytest"),
    ),
    ChangedOwner(
        owner_id="intake_project",
        path_prefixes=("src/sciplot_core/intake/",),
        owned_test_paths=frozenset(
            {
                "tests/test_intake_atomic_packaging.py",
                "tests/test_maintenance_integrity.py",
                "tests/test_source_recognition_contract.py",
            }
        ),
        pytest_targets=(
            "tests/test_intake_atomic_packaging.py",
            "tests/test_source_recognition_contract.py",
        ),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="generic_terminal_preparation",
        exact_paths=frozenset(
            {
                "src/sciplot_core/render/panel_render.py",
                "src/sciplot_core/render/public_api.py",
                "src/sciplot_core/render/target_paths.py",
                "src/sciplot_core/studio_core/prepare_generated.py",
                "src/sciplot_core/studio_core/prepare_generated_transaction.py",
                "src/sciplot_core/studio_core/prepare_existing.py",
                "src/sciplot_core/studio_core/figure_task_evidence.py",
                "src/sciplot_core/studio_core/series_request.py",
                "src/sciplot_core/studio_core/studio_prepare.py",
                "src/sciplot_core/preparation_source_attestation.py",
                "src/sciplot_core/terminal_source_attestation.py",
                "src/sciplot_core/terminal_source_binding.py",
                "src/sciplot_core/terminal_source_binding_wire.py",
                "src/sciplot_core/veusz_worker/operations.py",
                "src/sciplot_core/workflow/auto_split.py",
                "src/sciplot_core/workflow/request_rendering.py",
                "src/sciplot_core/workflow/single_task_bundle.py", "src/sciplot_core/qa/artifacts.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_generic_prepared_terminal_source.py",
                "tests/test_generic_single_task_plan.py",
                "tests/test_preparation_source_attestation.py",
                "tests/test_temperature_terminal_source_binding.py", "tests/test_artifact_raster_visibility.py",
            }
        ),
        pytest_targets=(
            "tests/test_generic_prepared_terminal_source.py", "tests/test_artifact_raster_visibility.py",
            "tests/test_generic_single_task_plan.py",
            "tests/test_preparation_source_attestation.py",
            "tests/test_temperature_terminal_source_binding.py::test_public_request_cannot_claim_prepared_terminal_source", "tests/test_temperature_terminal_source_binding.py::test_worker_binding_is_verified_once_at_worker_entry", "tests/test_temperature_terminal_source_binding.py::test_panel_seal_owns_single_parent_binding_validation",
            "tests/test_architecture_boundaries.py::test_terminal_source_binding_wire_has_only_two_runtime_importers",
            "tests/test_architecture_boundaries.py::test_veusz_worker_does_not_depend_on_the_studio_compatibility_facade",
            "tests/test_architecture_boundaries.py::test_veusz_worker_uses_named_studio_core_ports",
        ),
        final_milestone_gates=("smoke",),
        release_gates=("acceptance_rules", "full_pytest"),
    ),
    *GENERIC_AXIS_OWNERS,
    ChangedOwner(
        owner_id="native_series_revision",
        exact_paths=frozenset(
            {
                "src/sciplot_core/studio.py",
                "src/sciplot_core/studio_core/figure_set_storage.py",
                "src/sciplot_core/studio_core/guide_contracts.py",
                "src/sciplot_core/studio_core/persistence.py",
                "src/sciplot_core/studio_core/qt_window.py",
                "src/sciplot_core/studio_core/series_presentation.py",
                "src/sciplot_core/studio_core/series_revision_persistence.py",
                "src/sciplot_core/studio_core/veusz_series_revision.py",
                "src/sciplot_core/studio_core/veusz_series_revision_operations.py",
                "src/sciplot_core/veusz_worker/axis_matchers.py",
                "src/sciplot_core/veusz_worker/spec_audit/coordinator.py",
                "src/sciplot_core/veusz_worker/spec_audit/inventory.py",
                "src/sciplot_core/veusz_worker/spec_audit/series.py",
                "src/sciplot_gui/studio_project/bridge.py",
                "src/sciplot_gui/studio_project/dock.py",
                "src/sciplot_gui/studio_project/export_action.py",
                "src/sciplot_gui/studio_project/refresh.py",
                "src/sciplot_gui/studio_project/series_revision.py",
            }
        ),
        owned_test_paths=frozenset({"tests/test_veusz_series_revision.py"}),
        pytest_targets=(
            "tests/test_veusz_series_revision.py",
            "tests/test_studio_figure_task_chain.py::test_spec_task_mismatch_rolls_back_document_spec_and_registry",
            "tests/test_architecture_boundaries.py::test_studio_entry_modules_import_in_fresh_interpreters",
            "tests/test_architecture_boundaries.py::test_core_business_and_data_layers_do_not_depend_on_the_gui_layer",
            "tests/test_architecture_boundaries.py::test_gui_uses_the_public_studio_api_not_studio_core_implementation",
            *_ARCHITECTURE_CORE_TARGETS,
        ),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
)

IGNORED_CHANGED_PATHS = frozenset({"DEVELOPMENT_LOG.md"})

__all__ = ["CHANGED_OWNERS", "IGNORED_CHANGED_PATHS", "ChangedOwner"]
