"""Verification for semantic documents and their local transactional backend."""

from sciplot_core.verification.owner_model import ChangedOwner
from sciplot_core.verification.type_gate_owners import ARCHITECTURE_CORE_TARGETS


PLOT_TEST_PATHS = (
    "tests/test_family_style_overrides.py",
    "tests/test_rendering_profiles_helpers.py",
    "tests/test_rendering_profiles_text_equivalence.py",
    "tests/test_rendering_profile_mechanical.py",
    "tests/test_mechanical_rendering_profile_native.py",
    "tests/test_rheology_family_profiles_native.py",
    "tests/test_rendering_contract.py",
    "tests/test_rendering_regression.py",
    "tests/test_house_style_grammar.py",
    "tests/test_house_style_native.py",
    "tests/test_figure_grammar.py",
    "tests/test_figure_document.py",
    "tests/test_figure_layout.py",
    "tests/test_figure_backend_native.py",
    "tests/test_plot_ir.py",
    "tests/test_plot_transforms.py",
    "tests/test_managed_sources.py",
    "tests/test_managed_backend.py",
    "tests/test_managed_backend_native.py",
    "tests/test_managed_engine_native.py",
    "tests/test_managed_external_native.py",
    "tests/test_plot_external_mutation.py",
    "tests/test_managed_external_mutation.py",
    "tests/test_managed_rollback.py",
    "tests/test_managed_protocol_native.py",
    "tests/test_managed_recovery_native.py",
    "tests/test_managed_lifecycle_guards.py",
    "tests/test_managed_apply_recovery_native.py",
    "tests/test_managed_dependency_native.py",
    "tests/test_plot_adoption.py",
    "tests/test_plot_reimport.py",
    "tests/test_plot_reimport_native.py",
    "tests/test_native_process.py",
    "tests/test_native_process_native.py",
    "tests/test_plot_document.py",
    "tests/test_plot_cache.py",
    "tests/test_plot_content_store.py",
    "tests/test_plot_backend.py",
    "tests/test_plot_backend_native.py",
    "tests/test_plot_backend_semantics.py",
    "tests/test_plot_backend_semantics_native.py",
    "tests/test_plot_protocol.py",
    "tests/test_plot_protocol_native.py",
    "tests/test_plot_creation.py",
    "tests/test_plot_template_creation.py",
    "tests/test_plot_template_native.py",
    "tests/test_plot_engine.py",
    "tests/test_plot_engine_native.py",
)

PLOT_OWNER = ChangedOwner(
    owner_id="semantic_plot_engine",
    path_prefixes=("src/sciplot_core/native_process/", "src/sciplot_core/plot_document/", "src/sciplot_core/plot_backends/",
                   "src/sciplot_core/plot_engine/", "src/sciplot_core/plot_protocol/",
                   "src/sciplot_core/plot_ir/", "src/sciplot_core/plot_transforms/",
                   "src/sciplot_core/plot_grammar/", "src/sciplot_core/plot_layout/", "src/sciplot_core/rendering_contract/",
                   "tests/fixtures/rendering_profiles/"),
    exact_paths=frozenset({"src/sciplot_core/cli/parsers/plots.py", "src/sciplot_core/cli/dispatch/plots.py",
                          "src/sciplot_core/veusz_worker/persistent.py", "src/sciplot_core/qa/audit_support.py", "src/sciplot_core/qa/rendering_regression.py",
                          "src/sciplot_core/veusz_worker/managed.py", "tests/managed_plot_helpers.py",
                          "tests/fixtures/managed_normalize_executor.py", "tests/fixtures/figure_spec_v2.json",
                          "tests/rendering_profiles_helpers.py", "tests/rendering_profiles_native.py",
                          "tests/rendering_profile_mechanical.py", "tests/rendering_profile_mechanical_projection.py",
                          "tests/rheology_profile_helpers.py"}),
    owned_test_paths=frozenset(PLOT_TEST_PATHS),
    pytest_targets=(*PLOT_TEST_PATHS, *ARCHITECTURE_CORE_TARGETS),
    mypy_required=True,
    handoff_gates=("doctor",),
    final_milestone_gates=("smoke",),
    release_gates=("full_pytest",),
)
