"""Verification ownership for reviewed native project continuation."""

from sciplot_core.verification.owner_model import ChangedOwner


PROJECT_REVISION_OWNERS = (
    ChangedOwner(
        owner_id="native_project_change_ui",
        exact_paths=frozenset(
            {
                "src/sciplot_gui/studio_project/change_dialogs.py",
                "src/sciplot_gui/studio_project/change_worker.py",
                "src/sciplot_gui/studio_project/project_changes.py",
                "src/sciplot_gui/studio_project_services.py",
                "src/sciplot_gui/studio_project/services.py",
                "src/sciplot_gui/main_window_menu.py",
                "src/sciplot_gui/studio_project_status/provenance_status.py",
                "src/sciplot_gui/studio_project_status/workflow_status.py",
                "src/sciplot_gui/studio_project_status/builder.py",
                "src/sciplot_gui/studio_project/bridge.py",
                "src/sciplot_gui/studio_project/dock.py",
                "src/sciplot_gui/studio_project/refresh.py",
                "src/sciplot_gui/studio_project/export_action.py",
                "src/sciplot_gui/studio_project/series_revision.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_project_change_ui.py",
                "tests/test_project_change_ui_native.py",
            }
        ),
        pytest_targets=(
            "tests/test_project_change_ui.py",
            "tests/test_project_change_ui_native.py",
            "tests/test_studio_project_context.py",
            "tests/test_studio_project_status.py",
            "tests/test_architecture_boundaries.py",
        ),
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("full_pytest",),
    ),
    ChangedOwner(
        owner_id="reviewed_project_revision",
        exact_paths=frozenset(
            {
                "src/sciplot_core/studio_core/delivery_recovery.py",
                "src/sciplot_core/studio_core/delivery_recovery_state.py",
                "src/sciplot_core/studio_core/source_update.py",
                "src/sciplot_core/studio_core/source_update_commit.py",
                "src/sciplot_core/studio_core/source_update_review.py",
                "src/sciplot_core/studio_core/source_update_staging.py",
                "src/sciplot_core/veusz_worker/style_transfer.py",
                "src/sciplot_core/veusz_runtime.py",
                "src/sciplot_core/cli/dispatch/project_revision.py",
                "src/sciplot_core/cli/parsers/interfaces.py",
            }
        ),
        owned_test_paths=frozenset(
            {
                "tests/test_delivery_recovery.py",
                "tests/test_delivery_recovery_native.py",
                "tests/test_document_style_transfer.py",
                "tests/test_project_source_update.py",
                "tests/test_project_source_update_transaction.py",
                "tests/test_project_source_update_native.py",
                "tests/test_project_revision_cli.py",
                "tests/test_veusz_worker_thread_boundary.py",
            }
        ),
        pytest_targets=(
            "tests/test_delivery_recovery.py",
            "tests/test_delivery_recovery_native.py",
            "tests/test_document_style_transfer.py",
            "tests/test_project_source_update.py",
            "tests/test_project_source_update_transaction.py",
            "tests/test_project_source_update_native.py",
            "tests/test_project_revision_cli.py",
            "tests/test_veusz_worker_thread_boundary.py",
            "tests/test_architecture_boundaries.py",
            "tests/test_cli_surface.py",
        ),
        mypy_required=True,
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
        release_gates=("acceptance_rules", "full_pytest"),
    ),
    ChangedOwner(
        owner_id="pymupdf_import_compatibility",
        exact_paths=frozenset(
            {
                "src/sciplot_core/qa/pdf_text.py",
                "src/sciplot_core/qa/pdf_inspection.py",
                "src/sciplot_core/qa/pdf_graphics.py",
                "src/sciplot_core/intake/artifact_previews.py",
                "src/sciplot_core/visual_review/artifact_records.py",
            }
        ),
        pytest_targets=(
            "tests/test_visual_review.py",
            "tests/test_artifact_raster_visibility.py",
            "tests/test_delivery_studio_lifecycle.py",
        ),
        handoff_gates=("doctor",),
        final_milestone_gates=("smoke",),
    ),
)
